# For more information: https://laravel.com/docs/sail
version: '3'
services:
    eternumclub:
        build:
            context: .
            dockerfile: Dockerfile
        image: eternumclub:2.0
        container_name: eternumclub-php
        volumes:
            - .:/var/www/eternumclub
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - eternumclub
        depends_on:
            - mariadb
        working_dir: /var/www/eternumclub
    #Nginx Service for legacy
    nginx:
        image: nginx:1.21
        container_name: eternumclub-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/eternumclub
        ports:
            - "80:80"
        networks:
            - eternumclub
    #Phase2 Data Base
    mariadb:
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        container_name: eternumclub-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: eternumclub
            MYSQL_USER: eternumclub
            MYSQL_PASSWORD: eternumclub
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - backend:/var/lib/mysql
        networks:
            - eternumclub
    mailhog:
        image: mailhog/mailhog
        container_name: eternumclub-mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - eternumclub
networks:
    eternumclub:
        driver: bridge
volumes:
    backend:
        driver: local 
